### PR TITLE
Default to a stable scalaVersion

### PR DESCRIPTION
**Pull request by alexarchambault**
This PR proposes to make `scalaVersion` use the last _stable_ scala version from `.travis.yml` rather than simply the last one.

This matters e.g. when `2.13.0-M1` is in `.travis.yml`. In that case, if an older but stable scala version is present, like `2.12.2`, the latter will be used for `scalaVersion`.

This might be subjective, but this feels more natural to me to default to a stable version. (And this is in phase with Maven version intervals, like `[2.3;2.4)`, which are not supposed to match non stable versions either.)

### CODE REVIEW

**Comment by alexarchambault** [comment]
The failing tests are just fine locally... :-/

**Comment by dwijnand** [comment]
Heya @alexarchambault, thanks for the PR.

I'm happy with such a change, though it's a (semantically) breaking change so we'd probably want to bump the major version.

@djspiewak WDYT?

**Comment by djspiewak** [comment]
@dwijnand @alexarchambault I do like this change quite a lot.  I've run into this issue myself, and this is a nice solution.  My only concern is that the detection of what is a stable version seems a bit hacky, and definitely isn't going to work with Typelevel Scala.  Is there any way we can do better here?

BTW, sorry for the delay in responding.  Climbing out of inbox hell…

**Comment by dwijnand** [comment]
Wow, completely forgot about this PR...

> definitely isn't going to work with Typelevel Scala

Yeah we should be able to use utilities in CrossVersion. @alexarchambault if you don't get a chance I'll try and look at this the weekend.

**Comment by dwijnand** [comment]
This has a merge conflict now.

I'll close it as stale. But I think it's an interesting idea that I'd love to include, if anyone wants to respond to the feedback and resubmit this.

**Pull request closed without merging**
